#!/bin/bash
PATH=/bin:/usr/bin

die() {
    echo $* 1>&2
    exit 1
}

PARROT_HOME=$*
[ -d $PARROT_HOME/.git/svn ] || die "$PARROT_HOME is not a git-svn repo"
find $PARROT_HOME/.git/svn/refs/remotes/svn/* -name '.rev_map*' | xargs ./parse.pl | sort -n
